import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "../providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationMenuDemo } from "@/components/nav-bar";
import Footer from "@/_components/footer";
import ProviderApp from "@/providers/ProviderApp";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Oth-AI -Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-right" />
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <NavigationMenuDemo /> */}
            <ProviderApp children={children} />
            <Footer />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
